import type { Property, Lead, Deal, Activity, Requirement } from './schemas'

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Modern Downtown Penthouse',
    address: '456 Park Avenue',
    city: 'New York',
    state: 'NY',
    zip: '10022',
    price: 2500000,
    beds: 3,
    baths: 2.5,
    sqft: 2400,
    propertyType: 'condo',
    status: 'available',
    description: 'Luxury penthouse with stunning skyline views. High-end finishes throughout.',
    features: 'Pool access, Doorman, Fitness center, Modern kitchen, Hardwood floors',
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=500&h=400&fit=crop',
  },
  {
    id: '2',
    title: 'Suburban Family Home',
    address: '789 Oak Street',
    city: 'Portland',
    state: 'OR',
    zip: '97214',
    price: 675000,
    beds: 4,
    baths: 2,
    sqft: 2800,
    propertyType: 'house',
    status: 'pending',
    description: 'Beautiful family home in quiet neighborhood with large backyard.',
    features: 'Two-car garage, Updated kitchen, Hardwood floors, Master suite',
    imageUrl: 'https://images.unsplash.com/photo-1570129477492-45c003cedd38?w=500&h=400&fit=crop',
  },
  {
    id: '3',
    title: 'Urban Loft',
    address: '321 Industrial Way',
    city: 'Seattle',
    state: 'WA',
    zip: '98121',
    price: 450000,
    beds: 2,
    baths: 1,
    sqft: 1200,
    propertyType: 'condo',
    status: 'available',
    description: 'Trendy loft in artistic neighborhood with exposed brick and high ceilings.',
    features: 'Open concept, Exposed brick, High ceilings, In-unit laundry',
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=500&h=400&fit=crop',
  },
]

export const mockLeads: Lead[] = [
  {
    id: '1',
    firstName: 'John',
    lastName: 'Smith',
    email: 'john.smith@email.com',
    phone: '555-0101',
    budget: 500000,
    minBeds: 3,
    maxBeds: 4,
    location: 'Portland, OR',
    source: 'website',
    status: 'qualified',
    notes: 'Interested in family homes, flexible timeline',
  },
  {
    id: '2',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.j@email.com',
    phone: '555-0102',
    budget: 2000000,
    minBeds: 2,
    maxBeds: 3,
    location: 'New York, NY',
    source: 'referral',
    status: 'active',
    notes: 'Looking for luxury penthouse, quick closing needed',
  },
  {
    id: '3',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'mchen@email.com',
    phone: '555-0103',
    budget: 400000,
    minBeds: 1,
    maxBeds: 2,
    location: 'Seattle, WA',
    source: 'call',
    status: 'new',
    notes: 'First-time buyer, needs financing guidance',
  },
]

export const mockDeals: Deal[] = [
  {
    id: '1',
    leadId: '1',
    propertyId: '2',
    stage: 'visit',
    status: 'active',
    expectedCloseDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    offerPrice: 650000,
    notes: 'Scheduled showing for next Saturday',
  },
  {
    id: '2',
    leadId: '2',
    propertyId: '1',
    stage: 'negotiation',
    status: 'active',
    expectedCloseDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    offerPrice: 2400000,
    notes: 'Offer submitted, awaiting response',
  },
  {
    id: '3',
    leadId: '3',
    propertyId: '3',
    stage: 'match',
    status: 'active',
    expectedCloseDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    notes: 'Property matches buyer requirements',
  },
]

export const mockActivities: Activity[] = [
  {
    id: '1',
    type: 'call',
    leadId: '1',
    title: 'Initial consultation with John Smith',
    description: 'Discussed buyer needs and timeline. Interested in 3-4 bed homes.',
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    completed: true,
  },
  {
    id: '2',
    type: 'showing',
    propertyId: '2',
    leadId: '1',
    title: 'Property showing - 789 Oak Street',
    description: 'John and family viewed the property. Very interested.',
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    completed: true,
  },
  {
    id: '3',
    type: 'email',
    leadId: '2',
    title: 'Sent penthouse details to Sarah Johnson',
    description: 'Shared property listing and virtual tour link.',
    date: new Date(Date.now() - 8 * 60 * 60 * 1000),
    completed: true,
  },
  {
    id: '4',
    type: 'task',
    leadId: '1',
    title: 'Follow up with buyer about financing',
    description: 'Need to check mortgage pre-approval status',
    date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    completed: false,
  },
]

export const mockRequirements: Requirement[] = [
  {
    id: '1',
    leadId: '1',
    minPrice: 400000,
    maxPrice: 600000,
    minBeds: 3,
    maxBeds: 4,
    location: 'Portland, OR',
    propertyTypes: ['house', 'townhouse'],
    features: ['Garage', 'Backyard', 'Updated kitchen'],
    moveInDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    urgency: 'medium',
  },
  {
    id: '2',
    leadId: '2',
    minPrice: 1800000,
    maxPrice: 2500000,
    minBeds: 2,
    maxBeds: 3,
    location: 'New York, NY',
    propertyTypes: ['condo'],
    features: ['Pool', 'Doorman', 'Fitness center', 'Skyline view'],
    moveInDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    urgency: 'high',
  },
]
